### ISSUE TITLE
TO-DOs

### ISSUE THREAD

**Issue by MrMissx** [userbotindo/UserIndoBot#1]
### TO-DO list for [UserIndoBot](https://t.me/userbotindobot)

- [x] Migrate To [PTB v13](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Transition-guide-to-Version-13.0)
- [x] ~~Enable /setwelcome to reply~~
- [ ] Backup group Warns
- [ ] Backup group Filters
- [ ] Backup group Welcome

This TO-DO will updated every changes, bug found, issues confirmed, etc.
DO NOT report bug(s) here, Create a new issues to report.

**Comment by TomyPrs** [comment]
Kek /setwelcome reply text dah bisa 👍

**Comment by tomiprs0x** [comment]
Will never pixed
